import os


OPEN_BUS_MOT_KEY = os.environ.get('OPEN_BUS_MOT_KEY')
OPEN_BUS_SSH_TUNNEL_PRIVATE_KEY_FILE = os.environ.get('OPEN_BUS_SSH_TUNNEL_PRIVATE_KEY_FILE')
OPEN_BUS_SSH_TUNNEL_SERVER_IP = os.environ.get('OPEN_BUS_SSH_TUNNEL_SERVER_IP')
OPEN_BUS_SIRI_STORAGE_ROOTPATH = os.environ.get('OPEN_BUS_SIRI_STORAGE_ROOTPATH') or '.data/siri'
OPEN_BUS_S3_ENDPOINT_URL = os.environ.get('OPEN_BUS_S3_ENDPOINT_URL')
OPEN_BUS_S3_ACCESS_KEY_ID = os.environ.get('OPEN_BUS_S3_ACCESS_KEY_ID')
OPEN_BUS_S3_SECRET_ACCESS_KEY = os.environ.get('OPEN_BUS_S3_SECRET_ACCESS_KEY')
OPEN_BUS_S3_BUCKET = os.environ.get('OPEN_BUS_S3_BUCKET')
OPEN_BUS_S3_PATH_PREFIX = os.environ.get('OPEN_BUS_S3_PATH_PREFIX', 'stride-siri-requester')
OPEN_BUS_REQUESTER_TIMEOUT_SECONDS = int(os.environ.get('OPEN_BUS_REQUESTER_TIMEOUT_SECONDS') or '120')

HEALTH_DAEMON_PORT = int(os.environ.get('HEALTH_DAEMON_PORT') or '8081')
HEALTH_DAEMON_MAX_SECONDS_SINCE_LAST_SNAPSHOT = int(os.environ.get('HEALTH_DAEMON_MAX_SECONDS_SINCE_LAST_SNAPSHOT') or '240')
